
[postgres]
user = "postgres"
password = "xvzDV4curLidx8IWZJ6czDHQ1qa7wjfL"
dbName = "nla_db"
host = "postgres"
port = 5432
modelDir = ["./sql/model"]
viewDir = ["./sql/view"]
templateDir = ["./sql/template"]

[webServer]
enable = true
port = 3101
url = "https://example.ru"

[graylog]
host = "85.143.214.161"
port = 12201

[email]
sender = "info@nl-a.ru"
password = "mark12345"
host = "smtp.mail.ru"
port = 465
senderName = "NL!A"
isSendWithEmptySender = false








